package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Balanza generated by hbm2java
 */
public class Balanza  implements java.io.Serializable {


     private Integer idBalanza;
     private Cuenta cuenta;
     private Double saldoini;
     private Double cargos;
     private Double abonos;
     private Double saldofin;
     private Date fecha;
     private Date updated;

    public Balanza() {
    }

	
    public Balanza(Cuenta cuenta, Date fecha, Date updated) {
        this.cuenta = cuenta;
        this.fecha = fecha;
        this.updated = updated;
    }
    public Balanza(Cuenta cuenta, Double saldoini, Double cargos, Double abonos, Double saldofin, Date fecha, Date updated) {
       this.cuenta = cuenta;
       this.saldoini = saldoini;
       this.cargos = cargos;
       this.abonos = abonos;
       this.saldofin = saldofin;
       this.fecha = fecha;
       this.updated = updated;
    }
   
    public Integer getIdBalanza() {
        return this.idBalanza;
    }
    
    public void setIdBalanza(Integer idBalanza) {
        this.idBalanza = idBalanza;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Double getSaldoini() {
        return this.saldoini;
    }
    
    public void setSaldoini(Double saldoini) {
        this.saldoini = saldoini;
    }
    public Double getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Double cargos) {
        this.cargos = cargos;
    }
    public Double getAbonos() {
        return this.abonos;
    }
    
    public void setAbonos(Double abonos) {
        this.abonos = abonos;
    }
    public Double getSaldofin() {
        return this.saldofin;
    }
    
    public void setSaldofin(Double saldofin) {
        this.saldofin = saldofin;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}


