package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private Integer idConcepto;
     private Cuenta cuenta;
     private String nombre;
     private int codigo;
     private Date updated;
     private Set<Gasto> gastos = new HashSet<>(0);
     private Set<Factura> facturas = new HashSet<>(0);

    public Concepto() {
    }


    public Concepto(Cuenta cuenta, String nombre, int codigo, Date updated) {
        this.cuenta = cuenta;
        this.nombre = nombre;
        this.codigo = codigo;
        this.updated = updated;
    }
    public Concepto(Cuenta cuenta, String nombre, int codigo, Date updated, Set<Gasto> gastos, Set<Factura> facturas) {
       this.cuenta = cuenta;
       this.nombre = nombre;
       this.codigo = codigo;
       this.updated = updated;
       this.gastos = gastos;
       this.facturas = facturas;
    }

    public Integer getIdConcepto() {
        return this.idConcepto;
    }

    public void setIdConcepto(Integer idConcepto) {
        this.idConcepto = idConcepto;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }

    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }

    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }

    @Override
    public String toString() {
        return nombre;
    }

}


