package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private Empresa empresa;
     private Integer nivel;
     private String numeroCuenta;
     private String nombre;
     private String tipo;
     private String afecta;
     private String dig;
     private String edo;
     private String divisa;
     private Date fecha;
     private Date updated;
     private Set<Balanza> balanzas = new HashSet<Balanza>(0);
     private Set<Cueresultados> cueresultadoses = new HashSet<Cueresultados>(0);
     private Set<Lcuenta> lcuentas = new HashSet<Lcuenta>(0);
     private Set<Concepto> conceptos = new HashSet<Concepto>(0);

    public Cuenta() {
    }


    public Cuenta(Empresa empresa, String numeroCuenta, String divisa, Date fecha, Date updated) {
        this.empresa = empresa;
        this.numeroCuenta = numeroCuenta;
        this.divisa = divisa;
        this.fecha = fecha;
        this.updated = updated;
    }
    public Cuenta(Empresa empresa, Integer nivel, String numeroCuenta, String nombre, String tipo, String afecta, String dig, String edo, String divisa, Date fecha, Date updated, Set<Balanza> balanzas, Set<Cueresultados> cueresultadoses, Set<Lcuenta> lcuentas, Set<Concepto> conceptos) {
       this.empresa = empresa;
       this.nivel = nivel;
       this.numeroCuenta = numeroCuenta;
       this.nombre = nombre;
       this.tipo = tipo;
       this.afecta = afecta;
       this.dig = dig;
       this.edo = edo;
       this.divisa = divisa;
       this.fecha = fecha;
       this.updated = updated;
       this.balanzas = balanzas;
       this.cueresultadoses = cueresultadoses;
       this.lcuentas = lcuentas;
       this.conceptos = conceptos;
    }

    public Integer getIdCuenta() {
        return this.idCuenta;
    }

    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Integer getNivel() {
        return this.nivel;
    }

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }

    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getAfecta() {
        return this.afecta;
    }

    public void setAfecta(String afecta) {
        this.afecta = afecta;
    }
    public String getDig() {
        return this.dig;
    }

    public void setDig(String dig) {
        this.dig = dig;
    }
    public String getEdo() {
        return this.edo;
    }

    public void setEdo(String edo) {
        this.edo = edo;
    }
    public String getDivisa() {
        return this.divisa;
    }

    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set<Balanza> getBalanzas() {
        return this.balanzas;
    }

    public void setBalanzas(Set<Balanza> balanzas) {
        this.balanzas = balanzas;
    }
    public Set<Cueresultados> getCueresultadoses() {
        return this.cueresultadoses;
    }

    public void setCueresultadoses(Set<Cueresultados> cueresultadoses) {
        this.cueresultadoses = cueresultadoses;
    }
    public Set<Lcuenta> getLcuentas() {
        return this.lcuentas;
    }

    public void setLcuentas(Set<Lcuenta> lcuentas) {
        this.lcuentas = lcuentas;
    }
    public Set<Concepto> getConceptos() {
        return this.conceptos;
    }

    public void setConceptos(Set<Concepto> conceptos) {
        this.conceptos = conceptos;
    }

    @Override
    public String toString() {
        return nombre;
    }

}


