package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private String descripcion;
     private Date updated;
     private Set<Factura> facturas = new HashSet<>(0);
     private Set<Gasto> gastos = new HashSet<>(0);
     private Set<Cuenta> cuentas = new HashSet<>(0);

    public Empresa() {
    }


    public Empresa(Date updated) {
        this.updated = updated;
    }
    public Empresa(String nombre, String descripcion, Date updated, Set<Factura> facturas, Set<Gasto> gastos, Set<Cuenta> cuentas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.updated = updated;
       this.facturas = facturas;
       this.gastos = gastos;
       this.cuentas = cuentas;
    }

    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }

    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }

    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }

    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }

    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }

    @Override
    public String toString() {
        return nombre;
    }

}


