package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Concepto concepto;
     private Empresa empresa;
     private Date fecha;
     private String rfc;
     private String folio;
     private double importebruto;
     private double factoriva;
     private double importeiva;
     private double importe;
     private double importeutilizado;
     private String comentario;
     private Date updated;
     private Set<Gasto> gastos = new HashSet<Gasto>(0);

    public Factura() {
    }


    public Factura(Concepto concepto, Empresa empresa, Date fecha, String rfc, String folio, double importebruto, double factoriva, double importeiva, double importe, double importeutilizado, Date updated) {
        this.concepto = concepto;
        this.empresa = empresa;
        this.fecha = fecha;
        this.rfc = rfc;
        this.folio = folio;
        this.importebruto = importebruto;
        this.factoriva = factoriva;
        this.importeiva = importeiva;
        this.importe = importe;
        this.importeutilizado = importeutilizado;
        this.updated = updated;
    }
    public Factura(Concepto concepto, Empresa empresa, Date fecha, String rfc, String folio, double importebruto, double factoriva, double importeiva, double importe, double importeutilizado, String comentario, Date updated, Set<Gasto> gastos) {
       this.concepto = concepto;
       this.empresa = empresa;
       this.fecha = fecha;
       this.rfc = rfc;
       this.folio = folio;
       this.importebruto = importebruto;
       this.factoriva = factoriva;
       this.importeiva = importeiva;
       this.importe = importe;
       this.importeutilizado = importeutilizado;
       this.comentario = comentario;
       this.updated = updated;
       this.gastos = gastos;
    }

    public Integer getIdFactura() {
        return this.idFactura;
    }

    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }

    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getRfc() {
        return this.rfc;
    }

    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getFolio() {
        return this.folio;
    }

    public void setFolio(String folio) {
        this.folio = folio;
    }
    public double getImportebruto() {
        return this.importebruto;
    }

    public void setImportebruto(double importebruto) {
        this.importebruto = importebruto;
    }
    public double getFactoriva() {
        return this.factoriva;
    }

    public void setFactoriva(double factoriva) {
        this.factoriva = factoriva;
    }
    public double getImporteiva() {
        return this.importeiva;
    }

    public void setImporteiva(double importeiva) {
        this.importeiva = importeiva;
    }
    public double getImporte() {
        return this.importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }
    public double getImporteutilizado() {
        return this.importeutilizado;
    }

    public void setImporteutilizado(double importeutilizado) {
        this.importeutilizado = importeutilizado;
    }
    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set<Gasto> getGastos() {
        return this.gastos;
    }

    public void setGastos(Set<Gasto> gastos) {
        this.gastos = gastos;
    }

    @Override
    public String toString() {
        return rfc + " - " + folio;
    }

}


