package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lcuenta generated by hbm2java
 */
public class Lcuenta  implements java.io.Serializable {


     private Integer idLcuenta;
     private Cuenta cuenta;
     private Reporteesp reporteesp;
     private Date updated;

    public Lcuenta() {
    }

    public Lcuenta(Cuenta cuenta, Reporteesp reporteesp, Date updated) {
       this.cuenta = cuenta;
       this.reporteesp = reporteesp;
       this.updated = updated;
    }
   
    public Integer getIdLcuenta() {
        return this.idLcuenta;
    }
    
    public void setIdLcuenta(Integer idLcuenta) {
        this.idLcuenta = idLcuenta;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Reporteesp getReporteesp() {
        return this.reporteesp;
    }
    
    public void setReporteesp(Reporteesp reporteesp) {
        this.reporteesp = reporteesp;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}


