package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Llminicatalogo generated by hbm2java
 */
public class Minicatalogo  implements java.io.Serializable {
     private Integer idMinicatalogo;
     private String nombre;
     private String descripcion;
     private Date updated;
     private Set<Lminicatalogo> lminicatalogos = new HashSet<>(0);

    public Minicatalogo() {
    }

    public Minicatalogo(String nombre, String descripcion, Date updated, Set<Lminicatalogo> lminicatalogos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.updated = updated;
       this.lminicatalogos = lminicatalogos;
    }
   
    public Integer getIdMinicatalogo() {
        return this.idMinicatalogo;
    }
    
    public void setIdMinicatalogo(Integer idMinicatalogo) {
        this.idMinicatalogo = idMinicatalogo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public Set<Lminicatalogo> getLminicatalogos() {
        return lminicatalogos;
    }

    public void setLminicatalogos(Set<Lminicatalogo> lminicatalogos) {
        this.lminicatalogos = lminicatalogos;
    }

    @Override
    public String toString() {
        return nombre;
    }
}


