package kontreal.entities;
// Generated 16-may-2015 17:28:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reporteesp generated by hbm2java
 */
public class Reporteesp  implements java.io.Serializable {


     private Integer idReporteesp;
     private String nombre;
     private String descripcion;
     private Date updated;
     private Set<Lcuenta> lcuentas = new HashSet<Lcuenta>(0);

    public Reporteesp() {
    }

	
    public Reporteesp(String nombre, Date updated) {
        this.nombre = nombre;
        this.updated = updated;
    }
    public Reporteesp(String nombre, String descripcion, Date updated, Set<Lcuenta> lcuentas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.updated = updated;
       this.lcuentas = lcuentas;
    }
   
    public Integer getIdReporteesp() {
        return this.idReporteesp;
    }
    
    public void setIdReporteesp(Integer idReporteesp) {
        this.idReporteesp = idReporteesp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Set<Lcuenta> getLcuentas() {
        return this.lcuentas;
    }
    
    public void setLcuentas(Set<Lcuenta> lcuentas) {
        this.lcuentas = lcuentas;
    }




}


